name: imag-v2
channels:
  - defaults
dependencies:
  - ca-certificates=2023.08.22
  - libffi=3.4.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.8.18
  - setuptools=68.0.0
  - sqlite=3.41.2
  - wheel=0.41.2
  - pip:
      - blinker==1.7.0
      - click==8.1.7
      - colorama==0.4.6
      - flask==3.0.0
      - flask-cors==4.0.0
      - flask-sqlalchemy==3.1.1
      - greenlet==3.0.1
      - importlib-metadata==7.0.0
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - markdown==3.5.1
      - markupsafe==2.1.3
      - pillow==10.1.0
      - psycopg2==2.9.9
      - sqlalchemy==2.0.23
      - typing-extensions==4.8.0
      - werkzeug==3.0.1
      - zipp==3.17.0
